spring:
  profiles:
    active: "local"
  application:
    name: ecommerce-service
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:h2:mem:ecommercedb
    username: mjgamero
    password: mjgamero
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2/
      enabled: true